DEEPTEXT:
  # image_folder: 'demo_image/avc.png'
  workers: 4
  batch_size: 192
  saved_model: './src/models/deeptext.pth'
  batch_max_length: 25
  imgH: 32
  imgW: 100
  rgb: False
  character: '0123456789abcdefghijklmnopqrstuvwxyz'
  sensitive: False
  PAD: False
  Transformation: 'TPS'
  FeatureExtraction: 'ResNet'
  SequenceModeling: 'BiLSTM'
  Prediction: 'CTC'
  num_fiducial: 20
  input_channel: 1
  output_channel: 512
  hidden_size: 256



