PIPELINE:
  # text recog
  DEEPTEXT: True
  MORAN: False
  DEEPTEXT_MODEL_PATH: './models/best_accuracy.pth'
  MORAN_MODEL_PATH: './models/moran_model.pth'

  # pipeline
  Y_DIST_FOR_MERGE_BBOX: 5
  EXPAND_FOR_BBOX: 0
